font:
  normal:
    family: "MesloLGS NF"
    style: "Regular"
  bold:
    family: "MesloLGS NF"
    style: "Bold"
  italic:
    family: "MesloLGS NF"
    style: "Italic"
  bold_italic:
    family: "MesloLGS NF"
    style: "BoldItalic"
  size: 16
window:
  opacity: 0.9
  decorations: none
  padding:
    x: 20
    y: 20
