font:
  normal:
    family: "MesloLGSNerdFont"
    style: "Regular"
  bold:
    family: "MesloLGSNerdFont"
    style: "Bold"
  italic:
    family: "MesloLGSNerdFont"
    style: "Italic"
  bold_italic:
    family: "MesloLGSNerdFont"
    style: "BoldItalic"
  size: 12
window:
  opacity: 0.9
  decorations: none
  padding:
    x: 0
    y: 0
