#!/bin/sh

# Prints the status of monitors

default_screen="eDP"

connected_monitors=$(xrandr | grep " connected ")
last_port_connected=$(echo "$connected_monitors" | tail -n1 | cut -d' ' -f1)
num_monitors=$(echo "$connected_monitors" | wc -l)

case $num_monitors in
	1) xrandr --auto ;;
	*) xrandr --output $last_port_connected --auto --above $default_screen ;;
esac

nitrogen --restore > /dev/null

case $num_monitors in 
	1) ;;
	2) printf "🖥" ;;
	*) printf "🖥 $(($num_monitors - 1))" ;;
esac



case $BLOCK_BUTTON in
	1) xrandr --auto; nitrogen --restore ;;
	#2) xrandr --output $(HDMI-A-0); nitrogen --restore ;;
	3) killall -q notify-osd && notify-send "🖥 Monitors" "\- Displays number of connected devices if any.
- Click to open bluetoothctl
- Middle click to try to connect to all paired devices" ;;
	6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

